### ISSUE TITLE
Input button for recipes auto appended to the right of "Add Media" 

### ISSUE THREAD

**Issue by laralfield** [bwdinc/simmer#10]
@ChaseWiseman, what are your thoughts again on setting an 'Add Recipe' button to auto insert the necessary shortcode for the desired recipe? Can we use a feature exactly similar to the link tool for searching for content currently on the site here to allow users to select the recipe?

If you'd like, we can include a setting on the Simmer general settings page to turn off this feature with a checkbox if you think some users would prefer to always use the shortcode.

Thanks!

**Comment by ChaseWiseman** [comment]
I definitely think we should have some sort of interface for inserting recipe shortcodes, yes. I think the ability to search & select a recipe or multiple recipes would be key.

Ideally this wouldn't require its own new button, as I'd like to join the collective shift away from clogging up the UI with extra buttons. Interestingly, there is already an effort underway to add a standard shortcode UI to WordPress core [here](https://github.com/fusioneng/Shortcake). I added compatibility with that project back at Simmer v1.0.0, so we'll have a leg up when that gets finalized in the future.

But in the interim, I agree that we should have a temporary solution. Perhaps adding our own tab to the Add Media dialogue would work, with a divider below "Insert from URL":
![screen shot 2015-02-09 at 9 04 45 am](https://cloud.githubusercontent.com/assets/999301/6111046/d5bfa184-b03a-11e4-9318-1cbf087aa3f4.png)
From there you could search and select published recipes. I've never extended the new media modal UI so I'm not sure how flexible it is, but I'll start taking a look under the hood to see what we can accomplish!

**Comment by laralfield** [comment]
I'm fascinated to hear about the momentum behind a short code standard. This is great. But WP remains WYSIWYG on some features but not others. I just want to make sure we find the right balance for our users right now. 

In the interim, let's move ahead with the insert media option as it fits into your schedule. Sounds great. Thanks!
