### ISSUE TITLE
Descriptions included in recipe emebeds via shortcode?

### ISSUE THREAD

**Issue by laralfield** [bwdinc/simmer#12]
I have a quick question! Are recipes' desctipions, that is, the content entered in the main content area for a recipe, included in the embed for a recipe card, or above it in any way? Is this something we want to consider? In general, the idea I think should be to encourage users to keep the description area fairly straight forward and not drawn away from the exact recipe itself. It can be useful for including many more photos, and other key pieces of information for the recipe. So how do we make sure this is continually integrated in a great way? 

Thanks! Looking forward to your thoughts.

**Comment by ChaseWiseman** [comment]
Perhaps the solution here would be including the recipe excerpt. Then always linking the recipe title to the indiv. recipe page with of course has full TinyMCE content, etc...

**Comment by laralfield** [comment]
Yes! Sounds great. Can we also enable an elipses ... At the end of all excerpts?

**Comment by laralfield** [comment]
Hey Chase, an interesting example is that a lot of recipes feature notes, so maybe this is how our description field can work into the greater recipe cards' design, by default. 

http://bake2thefuture.com/2015/02/15/blood-orange-vanilla-bean-muffins-with-coconut/#.VOjwrlPF86n

I would just put it at the top, with no "Notes:" label needed :)
