### ISSUE TITLE
Prepend option for attribution name and link; default entry "Source":

### ISSUE THREAD

**Issue by laralfield** [bwdinc/simmer#13]
What do we think about including this as an option whe we have time to integrate it into the core? It makes sense sort of thinking about how photos are attributed in newspapers, etc... It would not be part of the linked text and would automatically include the colon punctuation. 

Let me know what you think. Thanks!

**Comment by ChaseWiseman** [comment]
Yes, I think this is a good idea. I'll also add an option to toggle it on/off, as well as change the label's text.

**Comment by laralfield** [comment]
Great! Super.
