### ISSUE TITLE
Default template structure

### ISSUE THREAD

**Issue by ChaseWiseman** [bwdinc/simmer#14]
As an ongoing priority, I'll be working on designing Simmer's template structure for a future release.

It wasn't in the scope at v1.0.0, but now that we're off and running we need to create a structure for fresh Simmer installs to automatically have:

* A recipe index (/recipes/). Just like the posts index, but with more relevant info to recipes.
* Recipe archives (/recipes/category/some-category/)
* Better single recipe formatting w/ featured images, etc...

These are all standard elements when adding a custom post type to someone's site and we should provide baseline compatibility for them on install. An example of great implementation is WooCommerce, which sets users up with all of the structures needed to have a working store. Luckily, ours will be far less complicated!

It'll be important to remember to keep development in check, however (I'm talking to myself), as we don't need to provide every bell and whistle out of the box. Rather, just a basic structure that can be built upon by other developers or our White Glove service.

**Comment by laralfield** [comment]
Super! I love the "less-complicated" factor, hehe. This is great, and I can't wait to demonstrate the value of this aspect of the product by showing how much business owners can extend upon these, either with their own developers or our own White Glove team.

Sounds great re: basic structure as well :)

**Comment by laralfield** [comment]
I thought that the recipes pages for this unique brand show a good example of a commercial/business context developers need for a project today: https://greenblender.com/smoothies/recipes/chocolate-maca-maple

Thanks!

**Comment by laralfield** [comment]
There are a few other great UX implementations (maybe around 4 I could gather) for recipes as well. Let me know anytime you'd like me and a few others to gather these further for a collaboration point in a Google Doc or something :)

**Comment by ChaseWiseman** [comment]
Yes, that is a great example of the direction I'd like to head for dealing with individual recipe views i.e. removing the "card" aspect in favor of a more tightly integrated template that's just as seamless as viewing a post. Then we can reserve the card template/styling for shortcode embedding within pages/posts only.

This will allow third-party devs to customize individual recipe views more easily and add any extra features like ads, sharing, etc... at their discretion using the provided actions/filters.

**Comment by laralfield** [comment]
Fantastic, yes, it really simplifies things and presents a content first approach in my mind.
