### ISSUE TITLE
Add text area recipe parsing option

### ISSUE THREAD

**Issue by ChaseWiseman** [bwdinc/simmer#18]
Users should be able to copy & paste ULs or OLs and have them automatically turned in to ingredients/instructions. Do our best to parse amounts away from descriptions.

Consider tabbed or modal for initial input.

**Comment by laralfield** [comment]
Yes, I think this would be great and was thinking about it the other night when entering a recipe. 

Let's consider a modal similar to the standard WordPress link input modal in the admin UI, but now that they have a newly dedicated UX team, I'm interested to see if this might change for them. Either way, I'm thinking we'll just go the most WordPress-native route. What do you think?
