### ISSUE TITLE
Recipe Importing

### ISSUE THREAD

**Issue by ChaseWiseman** [bwdinc/simmer#2]
The addition of a basic importer would be great. Namely, importing from just a URL. We will need to work out parsing of various large recipe website's content & APIs.

**Comment by laralfield** [comment]
I think this is a great central feature to focus on, as it can help a lot of existing food blogs, WordPress installations, etc... that already have a collection of recipes setup on Simmer easily and quickly. :+1:

**Comment by roblittlefield** [comment]
many plugins can pull the data from old posts via a highlight feature, not sure it's automated for anyo of them though. people are also very concerned what happens to the recipes if the plugin get's deactivated - some plugins have them disappear, others still display them as text.

**Comment by laralfield** [comment]
Hey Chase! Sharing my thoughts on this feature set via Slack. Then, I have a few starting thoughts: 

We ultimately need to pull at a minimum: title, description, list of ingredients, list of instructions, date, new slug/url, and category (if any) to create an individual recipe for Simmer. 

Next, we have to think about our typical starting scenarios for users of this extension:
1. WordPress sites publishing recipes simply as a part of posts
2. WordPress sites publishing using another recipe parser
3. Non-wordpress sites with RSS feeds with recipe data in each post

Let' start by making sure we think we have all of our typical starting use points accounted for, see if we're missing anything else, and then go from there. I think the RSS aspect for pt. 3 provides a key way for us to import and onboard new customers easily & efficiently. I think beyond that, a user or business should expect to complete manual entry, or work with us to create a script customized to their individual document (this, for example, could be great for someone with a super old library of recipes recently digitized, or something like that.) 

Thanks everyone!

**Comment by ChaseWiseman** [comment]
Good points about the data that needs to be added, though I think we should exclude Category as that should be set on the imported recipe's new home site since their categorization methods may differ. That, and I can see a user's site quickly ending up with lots of duplicate and unused categories.

After some initial brainstorming, here are the three main features I want to build out for the importer as a whole:

1. **Single recipe from URL** - Simply paste a recipe's URL from a known source and the data will be parsed and saved as a new recipe in WordPress. It's important that we fill in the attribution/"Inspired by..." link by default to encourage users to give credit to their sources.
2. **Single recipe as text** - I'd like to see a way for users to paste a text list (like this one!) into a text area and have it automagically be converted to Simmer ingredients. Same with Instructions.
3. **Basic XML/CSV import** - Similar to the standard WordPress content import. Allows folks to easily transfer their Simmer recipes between sites.

I think 2 & 3 will be a great release starting point, with the more complex # 1 being a followup improvement. Thoughts?

**Comment by laralfield** [comment]
Sounds great. I agree. I think we can also release the importer tool once 1
and 2 have been achieved. Leaving 3 for more iteration and work. What do
you think?

On Thursday, February 5, 2015, Chase Wiseman <notifications@github.com>
wrote:

> Good points about the data that needs to be added, though I think we
> should exclude Category as that should be set on the imported recipe's new
> home site since their categorization methods may differ. That, and I can
> see a user's site quickly ending up with lots of duplicate and unused
> categories.
>
> After some initial brainstorming, here are the three main features I want
> to build out for the importer as a whole:
>
>    1. *Single recipe from URL* - Simply paste a recipe's URL from a known
>    source and the data will be parsed and saved as a new recipe in WordPress.
>    It's important that we fill in the attribution/"Inspired by..." link by
>    default to encourage users to give credit to their sources.
>    2. *Single recipe as text* - I'd like to see a way for users to paste
>    a text list (like this one!) into a text area and have it automagically be
>    converted to Simmer ingredients. Same with Instructions.
>    3. *Basic XML/CSV import* - Similar to the standard WordPress content
>    import. Allows folks to easily transfer their Simmer recipes between sites.
>
> I think 2 & 3 will be a great release starting point, with the more
> complex # 1 being a followup improvement. Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bwdinc/simmer/issues/2#issuecomment-73079634>.
>


-- 
-- 

[image: BWD inc.]
[image: Lara Chelak, Founder & Chief Growth Hacker] [image: Lara on Twitter]
<http://twitter.com/laralfield> [image: Lara on LinkedIn]
<http://linkedin.com/in/lchelak/> [image: BWD on Instagram]
<http://instagram.com/gobwd>
[image: Phone: (888) 894-2947 ext. 700, 44 W. 28th St, 8th Fl, New York, NY
10001]

*COPY/PASTE ME:* Lara Littlefield: Founder, Chief Growth Hacker,
lara@gobwd.com
<https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=lara@gobwd.com>, (888)
894-2947 ext. 700, 44 W. 28th St, 8th Fl, New York, NY 10001

**Comment by ChaseWiseman** [comment]
While 3 is definitely the least exciting of the three, it'll absolutely need to be included from the start as that is basic functionality that every importer should have in my opinion.

Another area I think we can set ourselves apart is the entire importing workflow when adding lots of individual recipes. The XML/CSV import will take care of bulk imports, but let's consider a scenario where some poor soul has a ton of individual recipe URLs in front of them that need to be added. A great way to help our users in that regard would be to streamline the flow of adding each one. So rather than a separate "Import" settings page (where you would upload the aforementioned CSV) the import tools could be on the actual Add New Recipe admin screen. That way they would intuitively click Add New, and be given the option of manual input (default) or import (copy/paste or from URL). Once imported, they can go about cleaning up, reordering ingredients, etc...

**Comment by laralfield** [comment]
Definitely. I understand now and this looks like a great route, esp. re:
options to clean up later as they'd like because some recipe data is just
so unevenly spread and filled in by most online publishers of them.

Ok, great! Should I get together a list of the 2 other recipe plugins that
I think we should mention easy import support by name, or should we not
consider doing something that specific?

There are also a lot of paid WordPress themes specifically targeted towards
food, and one comes with 'Styling' for one of the more basic WP recipe
plugins out there. I'm going to chat with her first to see if we can get
some Simmer support in there in the long term, but in the meantime, if you
come across any food focused paid WP plugins we could potentially
collaborate with, let me know :)

On Thursday, February 5, 2015, Chase Wiseman <notifications@github.com>
wrote:

> While 3 is definitely the least exciting of the three, it'll absolutely
> need to be included from the start as that is basic functionality that
> every importer should have in my opinion.
>
> Another area I think we can set ourselves apart is the entire importing
> workflow when adding lots of individual recipes. The XML/CSV import will
> take care of bulk imports, but let's consider a scenario where some poor
> soul has a ton of individual recipe URLs in front of them that need to be
> added. A great way to help our users in that regard would be to streamline
> the flow of adding each one. So rather than a separate "Import" settings
> page (where you would upload the aforementioned CSV) the import tools could
> be on the actual Add New Recipe admin screen. That way they would
> intuitively click Add New, and be given the option of manual input
> (default) or import (copy/paste or from URL). Once imported, they can go
> about cleaning up, reordering ingredients, etc...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bwdinc/simmer/issues/2#issuecomment-73082990>.
>


-- 
-- 

[image: BWD inc.]
[image: Lara Chelak, Founder & Chief Growth Hacker] [image: Lara on Twitter]
<http://twitter.com/laralfield> [image: Lara on LinkedIn]
<http://linkedin.com/in/lchelak/> [image: BWD on Instagram]
<http://instagram.com/gobwd>
[image: Phone: (888) 894-2947 ext. 700, 44 W. 28th St, 8th Fl, New York, NY
10001]

*COPY/PASTE ME:* Lara Littlefield: Founder, Chief Growth Hacker,
lara@gobwd.com
<https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=lara@gobwd.com>, (888)
894-2947 ext. 700, 44 W. 28th St, 8th Fl, New York, NY 10001

**Comment by ChaseWiseman** [comment]
I think providing import support for other recipe plugins/themes is a good idea, but let's not declare support by name just yet. Once folks are using Simmer in greater numbers, perhaps we can gather feedback as to which pluginst/themes/services they'd like to see integration with and which will be worth solid dev time.

For v1 of this feature let's build the **CSV importing** with generic, Simmer-specific formatting. Mainly just a way to import/export between Simmer installs. If any of the existing plugins/services have exporting, I'll consider those in choosing a format so that things will be compatible but not specifically say "Import your recipes from X!" Down the line we can start adding and declaring specific third-party support as this feature grows.

**Comment by ChaseWiseman** [comment]
So that means right now we will have two main aspects to Simmer Importing out of the gate:

1. Copy/paste ingredients & instructions - This is the main draw and easiest way to quickly add recipes from other sources.
2. XML/CSV import - Import recipes previously exported from Simmer or from other sources with standard formatting.

And the future will hold URL importing and any other ideas we come up with for better importing down the line. Sound good?

**Comment by laralfield** [comment]
Perfectly said, and I think these 2 distinct options are great as well. 

Everything sounds good, looking forward to it :+1:

**Comment by ChaseWiseman** [comment]
Closing this to open specific issues for each import feature.
