### ISSUE TITLE
Add standard set of classes to body

### ISSUE THREAD

**Issue by ChaseWiseman** [bwdinc/simmer#20]
Helper classes for folks needing to style (where applicable):

* simmer
* simmer-recipe
* simmer-archive
* simmer-term
* simmer-category

Possibly more to come.

**Comment by laralfield** [comment]
:+1: Awesome for future styling by our users and to include in our documentation.

**Comment by laralfield** [comment]
Good content for WordPress theming or 3rd party add-on documentation?
