### ISSUE TITLE
Custom measurement amounts

### ISSUE THREAD

**Issue by laralfield** [bwdinc/simmer#26]
Kristen, one of our current customers, and I were talking about including a "drop" of something in her ingredients lists. Which brought me to the idea that it might just make sense to allow users the ability to customize their amount descriptions and types. 

In her case, the solution of course is just to write "drops of ___" into the ingredients name line itself. 

Anyways, I'm really thinking that this kind of feature enhancement is extension territory, as there are a few more things we could add (such as controlling even the way your abbreviations vs. full measurement amounts appear), but want to gather your feedback too anytime this week, @ChaseWiseman.

**Comment by ChaseWiseman** [comment]
Yes, I can imagine that plenty of folks will want to add oft-used custom measurement units to the dropdown. The ability to add/subtract units can already be harnessed by developers using the `simmer_get_units` filter.

As far as adding the ability to edit the units via an admin screen, I agree that it shouldn't be in core. I want to keep in line with the "decisions, not options" mantra so as to not overload the settings screen with 1,000 inputs, so adding a "units admin" through an extension would likely be the best way to go. Whether this should be its own extension or part of a larger extension can be up for discussion in the future. Or if a third-party dev creates one in the meantime, that's great too!

**Comment by laralfield** [comment]
Awesome! Love all of this. You know me: the more content we can pull out of this the better, so anytime you want to maybe pen a quick blog post from a developer's perspective just about the simmer_get_units filter (or maybe another preferred function or aspect of the code) feel free. Thanks!
