### ISSUE TITLE
X.X release welcome screen

### ISSUE THREAD

**Issue by ChaseWiseman** [bwdinc/simmer#33]
I'd like to implement a fresh-upgrade welcome screen as has become standard in numerous popular plugins and in WordPress itself. This will largely mirror the release blog posts with new feature highlights, screenshots (gifs?) and a overall change log.

**Comment by laralfield** [comment]
This sounds awesome. Yea, we can totally do .gifs, too :) Let me know what UI interactions you want to capture and I can help, or feel free to just run with it. Here's https://gyazo.com/ in case again. Just let me know.

**Comment by ChaseWiseman** [comment]
Rethinking this a little bit:

I don't think auto-directing to a welcome screen after upgrade is the right move, as I'd like to avoid hijacking the user's browser in that way. Instead, I think showing this "new features!" welcome screen the first time they visit the Simmer settings page after upgrade is a better direction. Then they can continue on to the regular settings page, and will see the welcome again when another x.x release comes.

**Comment by laralfield** [comment]
That sounds like a great compromise. This way, the user feels they have a choice in viewing this new information. 

I think this is a great place to insert the updates note into the flow of Simmer. 👍
