### ISSUE TITLE
Widget brainstorming

### ISSUE THREAD

**Issue by laralfield** [bwdinc/simmer#4]
It would be interesting to consider what type of widgets might be most useful to Simmer users, if any make sense to fit as part of the core. Interested in any further thoughts!

**Comment by ChaseWiseman** [comment]
Yes, I think considering some standard widgets that are included by default would be a great idea.

Off the top of my head:

* Recent Recipes - just like latest posts, in chronological order
* Categories - with options for sorting, count, etc...

Open to any further suggestions!

**Comment by laralfield** [comment]
Ingredients tag cloud! But I think that might be set aside for an ingredients related extension. :) 

Sounds great, let's start with these 2 widgets for no as a next-step item for the Simmer core.

**Comment by laralfield** [comment]
Should we add a time stamp, such as x hours ago to our recent recipes, or just leave it to titles in a UL? 

Categories are easy :)

**Comment by ChaseWiseman** [comment]
I think a relative timestamp is a great idea, though maybe with a checkbox on the widget's settings to make it optional.

**Comment by laralfield** [comment]
Great! We can move forward here as soon as you feel we have a set road map for #2.

**Comment by laralfield** [comment]
Is the time stamp idea good for v1 of this added feature or should we should we push it for a later iteration?

**Comment by ChaseWiseman** [comment]
We'll see how it comes along but it shouldn't be an issue. In general I'm going to try to stick to milestone dates rather than adjust those dates around specific features. I've slated this for the 1.1.0 milestone so anything release-ready will be included in that version.

**Comment by laralfield** [comment]
"Random" idea for a Random Recipe Title + Excerpt generator. Simple, and random on each load. JUst a thought :)

**Comment by ChaseWiseman** [comment]
Closing this issue now that the widget structure is in place, complete with Recent Recipes & Recipe Categories as standard widgets. Let's take any further brainstorming of new widgets to Slack. When a new widget is up for inclusion, we can open a new issue for it. Cheers!

**Comment by laralfield** [comment]
Sounds good, thanks! :+1:
