### ISSUE TITLE
Add post revisions support

### ISSUE THREAD

**Issue by laralfield** [bwdinc/simmer#43]
Today, I clicked on a "restore" link for a version of the bluberry recipe that was newer than the one I had loaded, on simmerwp.com. I then saw this screen, and click "Restore":

![screen shot 2015-04-20 at 1 11 24 pm](https://cloud.githubusercontent.com/assets/1518034/7236061/6c8647d8-e760-11e4-891a-b8e8bdad1932.png)

The restore didn't occur, and instead the screen was reloaded to the WordPress dashboard. This makes sense as I don't think we yet have versioning for recipes as an available Screen Option on the edit screen for a recipe. What do you think of adding it, and adding this functionality? Or, we could disable the messages that

**Comment by ChaseWiseman** [comment]
Yes, this is doable. Adding revision support for the recipe title, content, and other standard "post" features is simple. However, WordPress doesn't keep revisions of post meta by default, which in our case is the instructions and ingredients, that that will have to be added manually, likely after the new Items API from issue #36 is complete.

**Comment by laralfield** [comment]
Sounds great, yes, we'll focus on #36, and #35, and go from there. Thanks!

**Comment by ChaseWiseman** [comment]
Closing this as covered in #52
