### ISSUE TITLE
Focus on first input when adding ingredients/instructions

### ISSUE THREAD

**Issue by ChaseWiseman** [bwdinc/simmer#5]
A great way to speed up adding ingredients/instructions would be to automatically focus the cursor on the first input for the new item whenever a new item is added, saving the user a click.

**Comment by laralfield** [comment]
I agree; any small details like this to increase conversion to the recipe being completed I think are great. In the future, we can setup different user scenario studies, and record how many clicks each task takes, and what we can do to further optimize in a variety of areas. :+1:
