### ISSUE TITLE
Revisiting custom measurment types

### ISSUE THREAD

**Issue by laralfield** [bwdinc/simmer#50]
This great piece of feedback comes from Melissa Clark, who's been giving us some great feedback, and who recently finished up culinary school in California about 2 years ago. She wanted to add a "sprig" of ____ (rosemary, thyme, etc...) and this question came up. 

I know that in our last conversation we had discussed getting custom measurement types into its own extension, but I'm wondering if this functionality makes enough sense to marry it straight into the core plugin. @ChaseWiseman, what do you think, and feel free to fill in any holes I've overlooked here. 

For easy reference: https://docs.google.com/document/d/1f-MiKSqXH76ToafIEPzy41PwxvVrj-v-MUXQ07YXYoM/edit

Might we be best off for now keeping this for its own extension down the line, and simply adding "sprig" for now? It's a fairly common unit in American recipes. Thanks all!

**Comment by laralfield** [comment]
"The only thing I can think of as far as units of measure that I tend to veer towards are "scant" vs "heaping" tablespoons/teaspoons/cups?  Oh and also just a handful of something like greens.  I'm so friggin' imprecise!  But I hate the idea of people standing there being so fussy about my food, I want them to learn to be intuitive and shoot from the hip!"

More from Melissa :) The above might make sense for a "cooking without measurements" extension if some chefs really prefer that, and they can then use more descriptive things like "a heaping tablespoon" or a "handfull" or "pinch." Might be a neat "mode" to put measurements in. Anyways, we can leave this all on theback burner until we're ready for it. Thanks!

**Comment by ChaseWiseman** [comment]
Interesting angles to consider, for sure. Technically speaking custom measurement units are already possible by just skipping the `<select>` field and typing "sprig of thyme" into the description box, which has the exact same result on the front-end as if "sprig" were available from the unit `<select>` field.

But it sounds like this is less about how the data is saved and more of a UX consideration for the best input flow when adding a single ingredient. At first thought, maybe switching the `<select>` field to a text input w/ autocomplete (Select2) would be a good move. In the case, either way the user is typing _something_ into the _Unit_ field so they don't feel like they're skipping a step, and if what they type in is a standard unit like tbsp, then those items will match up.

Really the only reasons that we have preset units of measure in the first place are:

1. They can be converted - consider an extension that adds front-end conversion to metric units.
2. They're reusable which means less typing for the user.

The standard units of measure satisfy those two points, but we just need to consider what to do with units that don't make sense for point 1, i.e. a "dash" or "sprig" that can't be converted to anything else.

Is it possible to get more feedback from Melissa regarding her "ideal" flow for inputing regular ingredients as well as these custom ideas?

**Comment by laralfield** [comment]
Absolutely! I'll have a chat with her tonight or tomorrow, and will review all of this. Awesome.

**Comment by laralfield** [comment]
I'm going to close this one for now, after discussing with Melissa, and explaining that "spring" is a descriptor that fits maybe best as the actual ingredient line itself. 

Yes, an Extension for conversions I think will work best with our current drop down, and I don't want to increase it beyond what we have, and I think it's important to have them appear in the drop down visually so that chefs can easily recall and record things in the kitchen or elsewhere :) 

Thanks!
