### ISSUE TITLE
Ingredient items switching to sub-headings under ingredient section upon save

### ISSUE THREAD

**Issue by laralfield** [bwdinc/simmer#65]
When saving a draft, after using the bulk import tool to import a list of ingredients, the ingredient items revert to sub-heading entries after updating and reloading. This is using Simmer for Recipes on a pretty fresh WP install with the twentyfifteen theme :)

![screen shot 2015-06-09 at 8 51 49 pm](https://cloud.githubusercontent.com/assets/1518034/8072809/97fe84c4-0ee9-11e5-8ea9-76d4f82cd713.png)

![screen shot 2015-06-09 at 8 50 46 pm](https://cloud.githubusercontent.com/assets/1518034/8072811/9b7ad9a4-0ee9-11e5-8528-3ad1082c65db.png)

**Comment by ChaseWiseman** [comment]
This should be fixed in v1.3.4 via f7014ddd421efe71d46dda8c6aaa94e3c2c8f04e
